name: Run Calculator Script

on: [push, pull_request]  # 触发条件，这里设置为在push和pull_request时触发

jobs:
  build:
    runs-on: windows-latest  # 指定运行环境为最新的Windows

    steps:
    - uses: actions/checkout@v2  # 检出代码到运行环境

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 指定Python版本

    - name: Run Calculator Script
      run: python open_calculator.py  # 运行你的脚本
